name: Auto Merge Pull Request

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
  pull_request_review:
    types: [ submitted ]
  check_suite:
    types: [ completed ]
    status: { }


jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
