name: Auto Merge Pull Request

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check for approvals
        id: approval-check
        uses: actions/github-script@v6
        with:
          script: |
            const approvedUsers = ['avigailadam', 'pimkgirl']; // Replace with GitHub usernames
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const approved = reviews.some(review =>
              approvedUsers.includes(review.user.login) && review.state === 'APPROVED'
            );

            core.exportVariable('APPROVAL_STATUS', approved);
      - name: Print approval status
        run: |
          echo Approval status: $APPROVAL_STATUS
