name: Auto Merge Pull Request

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    pull_request_review:
      types: [submitted]
    check_suite:
      types: [completed]
      status: {}

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto merge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
