name: Notify Approvers

on:
  pull_request:
    types: [
      opened, edited, labeled, unlabeled, synced,
      synchronize, ready_for_review, reopened ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || secrets.PAT_TOKEN }}
          reviewers: pimkgirl
          skipKeywords: wip, draft